name: ytodos
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  go_router: ^13.2.0
  riverpod: ^2.5.0
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  easy_localization: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/translations/en-US.json
    - assets/images/
  fonts:
      - family: Raleway
        fonts:
          - asset: resources/fonts/Raleway-Heavy.ttf
            weight: 900
          - asset: resources/fonts/Raleway-ExtraBold.ttf
            weight: 800
          - asset: resources/fonts/Raleway-Bold.ttf
            weight: 700
          - asset: resources/fonts/Raleway-SemiBold.ttf
            weight: 600
          - asset: resources/fonts/Raleway-Medium.ttf
            weight: 500
          - asset: resources/fonts/Raleway-Regular.ttf
            weight: 400
          - asset: resources/fonts/Raleway-Light.ttf
            weight: 300
          - asset: resources/fonts/Raleway-ExtraLight.ttf
            weight: 200
          - asset: resources/fonts/Raleway-Thin.ttf
            weight: 100
